version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Recherche des dépendances
          command: apt-get update && apt-get -y install cmake ninja-build build-essential
      - run:
          name: Génération du dossier de build et creation du projet cmake
          command: mkdir build && cd build && cmake ../ -G Ninja
      - run:
          name: Compilation du code c++
          command: cd build && ninja

